### ISSUE TITLE
USER STORY: Book an appointment with a specific barber

### ISSUE THREAD

**Issue by JamieB92** [JamieB92/Agile-Project#3]
As a **customer of the barbershop** I can **book an appointment** so that **I can guarantee an appointment at a time that suits me best with my chosen barber**

### Acceptance Criteria

1.  Allow the customer to choose their barber of choice 
2.  Allow the customer to book in with anyone
3.  Allow the customer to select to choose and date and time
4.  Show all available appointments on that date and book the time of their choice
5.  Send the user a confirmation of the appointment

### Tasks

- [ ]  Create HTML & CSS for a booking page
- [ ]  Create a database to store the information
- [ ]  Link the login page as the user will need to login or create an account first
- [ ]  Create a barber selector with a image of each barber and a anyone option
- [ ]  Create a customer form with the customers details
- [ ]  Add a calendar plugin 
- [ ]  Add time selectors that shows all the available appointments
- [ ]  Add treatment selector 
- [ ]  Once Booked send customer an email with a confirmation
