### ISSUE TITLE
USER STORY: As a barber at the shop I would like to view, edit and delete my bookings

### ISSUE THREAD

**Issue by JamieB92** [JamieB92/Agile-Project#4]
As a **barber at the shop** I can **view, edit and delete my bookings** so that **so I can manage my time**

### Acceptance Criteria

1.  Allow the barbers of the shop to have a separate login to the site
2.  Allow the barber to view all of their bookings
3.  Allow the barber to edit, cancel and book their appointments

### Tasks

- [ ]  Create logins for the barbers
- [ ]  Create profile page which shows their appointments
- [ ]  Link the live data to the page
- [ ]  Allow the employee to cancel bookings
- [ ]  Create a book new appointment that takes them to the booking page
